export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_MACHINE_DATA = 'SET_MACHINE_DATA';
export const SET_PANEL_DATA = 'SET_PANEL_DATA';
export const SET_STATISTICS_DATA = 'SET_STATISTICS_DATA';
